'use strict';
class Unit{constructor(o){Object.assign(this,o);this.x=o.x;this.y=o.y;this.baseX=o.x;this.baseY=o.y;this.maxHp=o.hp;this.hp=o.hp;this.shield=0;this.energy=0;this.attackCd=rand(.15,.5);this.skillCd=rand(2.5,4.3);this.dead=false;this.hitFlash=0;this.anim=rand(0,10);this.ultFlash=0;this.taunt=0;this.bonusAtk=o.bonusAtk||1;this.bonusDef=o.bonusDef||1;}get hpPct(){return this.hp/this.maxHp}}
function buildPlayerUnits(){return save.formation.map((id,i)=>{const d=heroDefs[id],m=levelMult(id),sl=slotsPlayer[i];let bonusAtk=1,bonusDef=1;if(sl.front&&d.role==='Tank')bonusDef=1.25;if(!sl.front&&(d.role==='Ranger'||d.role==='Mage'))bonusAtk=1.15;if(!sl.front&&d.role==='Support')bonusAtk=1.12;return new Unit({id,name:d.name,role:d.role,color:d.color,code:d.code,side:'p',slot:i,x:sl.x,y:sl.y,hp:d.hp*m,atk:d.atk*m,def:d.def*m,spd:d.spd,range:d.range,bonusAtk,bonusDef});});}
function enemyDefsForStage(){const s=save.stage,m=1+(s-1)*.07;return [{id:'en_tank',name:'RIOT',role:'Tank',color:'#ff5e68',hp:980*m,atk:77*m,def:34*m,spd:.88,range:150},{id:'en_fighter',name:'RAZE',role:'Fighter',color:'#ff8b4d',hp:820*m,atk:104*m,def:23*m,spd:1.02,range:170},{id:'en_sniper',name:'HEX',role:'Ranger',color:'#ff4f9d',hp:590*m,atk:125*m,def:12*m,spd:1.1,range:470},{id:'en_mage',name:'NULL',role:'Mage',color:'#a968ff',hp:610*m,atk:118*m,def:14*m,spd:1.0,range:430},{id:'en_assassin',name:'WRAITH',role:'Assassin',color:'#ff294f',hp:640*m,atk:136*m,def:13*m,spd:1.22,range:175}];}
function buildEnemyUnits(){return enemyDefsForStage().map((d,i)=>{const sl=slotsEnemy[i];return new Unit({...d,side:'e',slot:i,x:sl.x,y:sl.y,bonusAtk:1,bonusDef:sl.front&&d.role==='Tank'?1.2:1});});}
function addFx(type,src,tgt,color,life=.24,extra={}){if(!src)return;combatFx.push({type,x1:src.x,y1:src.y-8,x2:tgt?tgt.x:src.x,y2:tgt?tgt.y-8:src.y-8,color,life,maxLife:life,flip:src.side==='e',...extra});}
function resetPrep(){state='prep';resultShown=false;battleTime=60;selectedHero=null;protocolBanner=null;units=[...buildPlayerUnits(),...buildEnemyUnits()];particles=[];floaters=[];combatFx=[];els.timer.textContent='ГОТОВНОСТЬ';els.mode.textContent='ДИСЛОКАЦИЯ';els.tip.textContent='Выбери оперативника и вторую позицию — бойцы поменяются местами.';els.start.disabled=false;els.modal.classList.remove('show');updateHUD();}
function startBattle(){if(state!=='prep')return;state='battle';battleTime=60;selectedHero=null;renderRoster();updateDossier();els.mode.textContent='АВТОБОЙ';els.tip.textContent='Оперативники работают автономно. Энергия активирует боевые протоколы.';els.start.disabled=true;els.upgrade.disabled=true;toastMsg('Операция началась. Канал VANTA синхронизирован.');}
function living(side){return units.filter(u=>u.side===side&&!u.dead)}function enemiesOf(u){return living(u.side==='p'?'e':'p')}function alliesOf(u){return living(u.side)}function slotInfo(u){return (u.side==='p'?slotsPlayer:slotsEnemy)[u.slot]}
function chooseTarget(u){const es=enemiesOf(u);if(!es.length)return null;if(u.role==='Assassin'){const back=es.filter(e=>!slotInfo(e).front),pool=back.length?back:es;return pool.slice().sort((a,b)=>a.hpPct-b.hpPct)[0];}const taunters=es.filter(e=>e.taunt>0);if(taunters.length)return taunters[0];if(u.role==='Ranger'||u.role==='Mage')return es.slice().sort((a,b)=>a.hpPct-b.hpPct)[0];return es.slice().sort((a,b)=>dist(u,a)-dist(u,b))[0];}
function damage(src,tgt,amount,critChance=.08){if(!tgt||tgt.dead)return;const crit=Math.random()<critChance;let dmg=amount*(crit?1.65:1)*(100/(100+tgt.def*tgt.bonusDef));if(tgt.shield>0){const s=Math.min(tgt.shield,dmg);tgt.shield-=s;dmg-=s;if(s>0)floaters.push({x:tgt.x,y:tgt.y-54,text:`-${Math.round(s)}`,color:'#63e8ff',life:.7});}if(dmg>0){tgt.hp-=dmg;tgt.energy=clamp(tgt.energy+8,0,100);tgt.hitFlash=.12;shake=Math.max(shake,crit?7:3);floaters.push({x:tgt.x+rand(-12,12),y:tgt.y-64,text:(crit?'КРИТ ':'')+Math.round(dmg),color:crit?'#ffd36b':'#ffffff',life:.75});}if(tgt.hp<=0){tgt.hp=0;tgt.dead=true;burst(tgt.x,tgt.y,tgt.color,15);addFx('pulse',tgt,null,tgt.color,.35);}}
function heal(src,tgt,amount){if(!tgt||tgt.dead)return;const before=tgt.hp;tgt.hp=Math.min(tgt.maxHp,tgt.hp+amount);const v=tgt.hp-before;if(v>0){floaters.push({x:tgt.x,y:tgt.y-64,text:`+${Math.round(v)}`,color:'#72ffb3',life:.9});addFx('heal',src,tgt,'#55f1d0',.42);}}
function burst(x,y,color,n=8){for(let i=0;i<n;i++)particles.push({x,y,vx:rand(-120,120),vy:rand(-150,60),life:rand(.25,.65),color,size:rand(3,8)});}
function basicAttack(u,t){u.attackCd=1/u.spd;u.energy=clamp(u.energy+17,0,100);u.x+=(u.side==='p'?1:-1)*10;setTimeout(()=>{if(!u.dead)u.x=u.baseX;},70);let mult=1;if(u.role==='Ranger'&&!slotInfo(u).front)mult*=1.12;if(u.role==='Mage'&&!slotInfo(u).front)mult*=1.08;if(u.role==='Ranger')addFx('tracer',u,t,u.color,.19);else if(u.role==='Mage')addFx('beam',u,t,u.color,.16);else if(u.role==='Assassin')addFx('slash',u,t,u.color,.22);else addFx('tracer',u,t,u.color,.14);damage(u,t,u.atk*u.bonusAtk*mult,u.role==='Assassin'?.18:.08);if(u.role==='Tank')u.taunt=.8;burst(t.x,t.y,u.color,3);}
function useSkill(u){u.skillCd=4.8+(u.role==='Tank'?.8:0);const foes=enemiesOf(u),friends=alliesOf(u);if(!foes.length)return;if(u.side==='e'){if(u.role==='Tank'){u.shield+=u.maxHp*.14;u.taunt=1.5;burst(u.x,u.y,u.color,6);addFx('pulse',u,null,u.color,.38);}else if(u.role==='Mage'){foes.slice().sort((a,b)=>a.hpPct-b.hpPct).slice(0,3).forEach(t=>{addFx('beam',u,t,u.color,.24);damage(u,t,u.atk*.75);});}else if(u.role==='Assassin'){const t=chooseTarget(u);addFx('slash',u,t,u.color,.28);damage(u,t,u.atk*1.55,.2);}else{const t=chooseTarget(u);addFx('tracer',u,t,u.color,.2);damage(u,t,u.atk*1.25,.12);}return;}switch(u.id){case'axel':u.shield+=u.maxHp*.22;u.taunt=2.1;burst(u.x,u.y,u.color,10);addFx('pulse',u,null,u.color,.46);break;case'nova':foes.slice().sort((a,b)=>a.hpPct-b.hpPct).slice(0,3).forEach(t=>{addFx('beam',u,t,u.color,.3);damage(u,t,u.atk*.72);});burst(W*.5,H*.5,u.color,10);break;case'bolt':{const t=chooseTarget(u);for(let i=0;i<3;i++)setTimeout(()=>{addFx('tracer',u,t,u.color,.18);damage(u,t,u.atk*.45,.16);},i*90);break;}case'vera':{const t=friends.slice().sort((a,b)=>a.hpPct-b.hpPct)[0];heal(u,t,u.atk*2.2*u.bonusAtk);break;}case'blade':{const t=chooseTarget(u);addFx('slash',u,t,u.color,.32);damage(u,t,u.atk*1.7,.28);break;}}}
function showProtocol(u){if(u.side!=='p')return;const d=heroDefs[u.id];protocolBanner={text:`${u.name} // ${d.protocol}`,color:u.color,life:1.05};}
function useUlt(u){u.energy=0;u.ultFlash=.5;shake=Math.max(shake,10);showProtocol(u);const foes=enemiesOf(u),friends=alliesOf(u);burst(u.x,u.y,u.color,18);addFx('pulse',u,null,u.color,.55);if(u.side==='e'){const t=chooseTarget(u);if(u.role==='Mage')foes.forEach(x=>{addFx('beam',u,x,u.color,.3);damage(u,x,u.atk);});else{addFx(u.role==='Assassin'?'slash':'tracer',u,t,u.color,.32);damage(u,t,u.atk*2,.15);}return;}switch(u.id){case'axel':friends.forEach(a=>a.shield+=a.maxHp*.18);break;case'nova':foes.forEach(t=>{addFx('beam',u,t,u.color,.38);damage(u,t,u.atk*1.25);});break;case'bolt':foes.slice().sort((a,b)=>a.hpPct-b.hpPct).slice(0,4).forEach((t,i)=>setTimeout(()=>{addFx('tracer',u,t,u.color,.25);damage(u,t,u.atk*.95,.2);},i*80));break;case'vera':friends.forEach(a=>heal(u,a,u.atk*1.6));break;case'blade':{const t=foes.slice().sort((a,b)=>a.hpPct-b.hpPct)[0];addFx('slash',u,t,u.color,.42);damage(u,t,u.atk*(t.hpPct<.35?3.1:2.1),.25);break;}}}
function updateBattle(dt){battleTime-=dt;els.timer.textContent=Math.max(0,battleTime).toFixed(1);for(const u of units){if(u.dead)continue;u.anim+=dt;u.hitFlash=Math.max(0,u.hitFlash-dt);u.ultFlash=Math.max(0,u.ultFlash-dt);u.taunt=Math.max(0,u.taunt-dt);u.attackCd-=dt;u.skillCd-=dt;if(u.energy>=100){useUlt(u);continue;}if(u.skillCd<=0){useSkill(u);continue;}if(u.attackCd<=0){const t=chooseTarget(u);if(t)basicAttack(u,t);}}if(!living('e').length)finish(true);else if(!living('p').length||battleTime<=0)finish(false);}
function finish(win){if(resultShown)return;resultShown=true;state='result';const currentSector=sectorData(),reward=win?120+save.stage*35:35;if(win){save.credits+=reward;save.stage+=1;}else save.credits+=reward;persist();setTimeout(()=>{els.resultTitle.textContent=win?'СЕКТОР ЗАЧИЩЕН':'ОТРЯД НЕЙТРАЛИЗОВАН';els.resultTitle.className='resultTitle '+(win?'win':'loss');els.resultReward.textContent=win?`+${reward} КРЕДИТОВ · ДОСТУП К СЕКТОРУ ${save.stage}`:`+${reward} КРЕДИТОВ · БОЕВАЯ ГРУППА ВОССТАНОВЛЕНА`;els.debrief.textContent=win?currentSector.debrief:'Измени дислокацию или проведи модификацию оперативников перед повторным входом.';els.next.style.display=win?'inline-block':'none';els.modal.classList.add('show');updateHUD();},450);}
function updateEffects(dt){particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=260*dt;p.life-=dt;});particles=particles.filter(p=>p.life>0);floaters.forEach(f=>{f.y-=42*dt;f.life-=dt;});floaters=floaters.filter(f=>f.life>0);combatFx.forEach(f=>f.life-=dt);combatFx=combatFx.filter(f=>f.life>0);shake=Math.max(0,shake-30*dt);if(protocolBanner){protocolBanner.life-=dt;if(protocolBanner.life<=0)protocolBanner=null;}}
